{% set python_min = "3.11" %}
{% set name = "nionutils" %}
{% set version = "4.14.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1478633d13718297cd9b701f4bd0c2f2e66a70298863efc20cba9f38c1f4eec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - nion.utils
    - nion.utils.test

about:
  home: https://github.com/nion-software/nionutils
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Nion utility classes.
  dev_url: https://github.com/nion-software/nionutils

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
